name: Deploy to Dev on Pull Request

on:
  pull_request:
    types: [opened, synchronize] # Runs when a PR is opened or new commits are pushed to it

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy PR branch to Dev Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the dev directory
            cd /var/www/outfrontyouth.org.dev
            
            # Add dev directory to Git's safe list
            git config --global --add safe.directory /var/www/outfrontyouth.org.dev
            
            # Fetch all branches from the remote repository
            git fetch --all
            
            # Check out the specific branch from the pull request
            # github.head_ref is a special variable holding the PR's branch name
            git checkout ${{ github.head_ref }}
            
            # Pull the latest changes for that branch
            git pull origin ${{ github.head_ref }}
